# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'threadgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 50, 311, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_button = QtWidgets.QPushButton(Dialog)
        self.start_button.setGeometry(QtCore.QRect(50, 210, 89, 25))
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(Dialog)
        self.stop_button.setGeometry(QtCore.QRect(260, 210, 89, 25))
        self.stop_button.setObjectName("stop_button")
        self.label_value = QtWidgets.QLabel(Dialog)
        self.label_value.setGeometry(QtCore.QRect(170, 180, 131, 20))
        self.label_value.setObjectName("label_value")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.start_button.setText(_translate("Dialog", "start"))
        self.stop_button.setText(_translate("Dialog", "stop"))
        self.label_value.setText(_translate("Dialog", "Value"))
